package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class AddOp implements java.io.Serializable {
    public abstract <T> T match(Function<Plus, T> plus,
                                Function<Minus, T> minus);

}
