package Latte.Absyn; // Java Package generated by the BNF Converter.


import java.util.function.Function;

public abstract class AddOp implements java.io.Serializable {
    public abstract <R, A> R accept(AddOp.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.Plus p, A arg);

        public R visit(Latte.Absyn.Minus p, A arg);

    }

    public abstract <T> T match(Function<Latte.Absyn.Plus, T> plus,
                                Function<Latte.Absyn.Minus, T> minus);

}
