package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Arg implements java.io.Serializable {

    public abstract <T> T match(Function<ArgTI, T> arg);

}
