package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Arg implements java.io.Serializable {
    public abstract <R, A> R accept(Arg.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.ArgTI p, A arg);

    }

    public abstract <T> T match(Function<Latte.Absyn.ArgTI, T> arg);

}
