package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ArgTI extends Latte.Absyn.Arg {
    public final Latte.Absyn.Type type_;
    public final String ident_;

    public ArgTI(Latte.Absyn.Type p1, String p2) {
        type_ = p1;
        ident_ = p2;
    }

    public <R, A> R accept(Latte.Absyn.Arg.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ArgTI) {
            Latte.Absyn.ArgTI x = (Latte.Absyn.ArgTI) o;
            return this.type_.equals(x.type_) && this.ident_.equals(x.ident_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.type_.hashCode()) + this.ident_.hashCode();
    }


    public <T> T match(Function<Latte.Absyn.ArgTI, T> arg) {
        return arg.apply(this);
    }


}
