package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ArgTI extends Arg implements Positioned {

    @Override
    public String getPosition() {
        return "(" + line_num + ", " + col_num + ")";
    }

    public final Type type_;
    public final String ident_;
    public int line_num, col_num, offset;

    public ArgTI(Type p1, String p2) {
        type_ = p1;
        ident_ = p2;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof ArgTI) {
            ArgTI x = (ArgTI) o;
            return this.type_.equals(x.type_) && this.ident_.equals(x.ident_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.type_.hashCode()) + this.ident_.hashCode();
    }

    public <T> T match(Function<ArgTI, T> arg) {
        return arg.apply(this);
    }
}
