package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ArrayType extends Latte.Absyn.Type {
    public final Latte.Absyn.TypeName typename_;
    public final Latte.Absyn.ListEmptyBracket listemptybracket_;

    public ArrayType(Latte.Absyn.TypeName p1, Latte.Absyn.ListEmptyBracket p2) {
        typename_ = p1;
        listemptybracket_ = p2;
    }

    public <R, A> R accept(Latte.Absyn.Type.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ArrayType) {
            Latte.Absyn.ArrayType x = (Latte.Absyn.ArrayType) o;
            return this.typename_.equals(x.typename_) && this.listemptybracket_.equals(x.listemptybracket_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.typename_.hashCode()) + this.listemptybracket_.hashCode();
    }


    public <T> T match(Function<Latte.Absyn.ArrayType, T> arrayType,
                       Function<Latte.Absyn.TypeNameS, T> typeNameS) {
        return arrayType.apply(this);
    }

}
