package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ArrayType  extends Type implements Positioned {

    @Override
    public String getPosition() {
        return "(" + line_num + ", " + col_num + ")";
    }
    public final TypeName typename_;
    public int line_num, col_num, offset;
    public ArrayType(TypeName p1) { typename_ = p1; }


    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ArrayType) {
            Latte.Absyn.ArrayType x = (Latte.Absyn.ArrayType)o;
            return this.typename_.equals(x.typename_);
        }
        return false;
    }

    public int hashCode() {
        return this.typename_.hashCode();
    }

    public <T> T match(Function<ArrayType, T> arrayType,
                       Function<TypeNameS, T> typeNameS) {
        return arrayType.apply(this);
    }
}
