package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ArrElemLhs extends Lhs implements Positioned {

    @Override
    public String getPosition() {
        return "(" + line_num + ", " + col_num + ")";
    }

    public final String ident_;
    public final Expr expr_;
    public int line_num, col_num, offset;

    public ArrElemLhs(String p1, Expr p2) {
        ident_ = p1;
        expr_ = p2;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ArrElemLhs) {
            Latte.Absyn.ArrElemLhs x = (Latte.Absyn.ArrElemLhs) o;
            return this.ident_.equals(x.ident_) && this.expr_.equals(x.expr_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.ident_.hashCode()) + this.expr_.hashCode();
    }

    public <T> T match(Function<VariableRawLhs, T> variableRawLhs,
                       Function<ArrElemLhs, T> arrElemLhs,
                       Function<FieldLhs, T> fieldLhs) {
        return arrElemLhs.apply(this);
    }
}
