package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class Ass extends Stmt {
    public final String ident_;
    public final Expr expr_;
    public int line_num, col_num, offset;

    public Ass(String p1, Expr p2) {
        ident_ = p1;
        expr_ = p2;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Ass) {
            Ass x = (Ass) o;
            return this.ident_.equals(x.ident_) && this.expr_.equals(x.expr_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.ident_.hashCode()) + this.expr_.hashCode();
    }

    public <T> T match(Function<Empty, T> empty,
                       Function<BStmt, T> bStmt,
                       Function<Decl, T> decl,
                       Function<Ass, T> ass,
                       Function<Incr, T> incr,
                       Function<Decr, T> decr,
                       Function<Ret, T> ret,
                       Function<VRet, T> vRet,
                       Function<Cond, T> cond,
                       Function<CondElse, T> condElse,
                       Function<While, T> sWhile,
                       Function<SExp, T> sExp) {
        return ass.apply(this);
    }
}
