package Latte.Absyn; // Java Package generated by the BNF Converter.

public class Ass extends Latte.Absyn.Stmt {
    public final String ident_;
    public final Latte.Absyn.Expr expr_;

    public Ass(String p1, Latte.Absyn.Expr p2) {
        ident_ = p1;
        expr_ = p2;
    }

    public <R, A> R accept(Latte.Absyn.Stmt.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.Ass) {
            Latte.Absyn.Ass x = (Latte.Absyn.Ass) o;
            return this.ident_.equals(x.ident_) && this.expr_.equals(x.expr_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.ident_.hashCode()) + this.expr_.hashCode();
    }


}
