package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class BlockS extends Latte.Absyn.Block {
    public final Latte.Absyn.ListStmt liststmt_;

    public BlockS(Latte.Absyn.ListStmt p1) {
        liststmt_ = p1;
    }

    public <R, A> R accept(Latte.Absyn.Block.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.BlockS) {
            Latte.Absyn.BlockS x = (Latte.Absyn.BlockS) o;
            return this.liststmt_.equals(x.liststmt_);
        }
        return false;
    }

    public int hashCode() {
        return this.liststmt_.hashCode();
    }


    public <T> T match(Function<Latte.Absyn.BlockS, T> blockS) {
        blockS.apply(this);
    }
}
