package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Block implements java.io.Serializable {
    public abstract <R, A> R accept(Block.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.BlockS p, A arg);

    }

    public abstract <T> T match(Function<Latte.Absyn.BlockS, T> blockS);

}
