package Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class BStmt extends Stmt {
    public final Block block_;
    public int line_num, col_num, offset;

    public BStmt(Block p1) {
        block_ = p1;
    }


    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof BStmt) {
            BStmt x = (BStmt) o;
            return this.block_.equals(x.block_);
        }
        return false;
    }

    public int hashCode() {
        return this.block_.hashCode();
    }

    public <T> T match(Function<Empty, T> empty,
                       Function<BStmt, T> bStmt,
                       Function<Decl, T> decl,
                       Function<Ass, T> ass,
                       Function<Incr, T> incr,
                       Function<Decr, T> decr,
                       Function<Ret, T> ret,
                       Function<VRet, T> vRet,
                       Function<Cond, T> cond,
                       Function<CondElse, T> condElse,
                       Function<While, T> sWhile,
                       Function<SExp, T> sExp) {
        return bStmt.apply(this);
    }
}
