package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class ClassHeader implements java.io.Serializable {
    public abstract <R, A> R accept(ClassHeader.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.ClassDec p, A arg);

        public R visit(Latte.Absyn.InterDec p, A arg);

    }


    public abstract <T> T match(Function<Latte.Absyn.ClassDec, T> classDec,
                                Function<Latte.Absyn.InterDec, T> interDec);

}
