package Latte.Absyn; // Java Package generated by the BNF Converter.

public class ClassDecl extends TopDef {
    public final ClassHeader classheader_;
    public final ListFieldDeclaration listfielddeclaration_;

    public ClassDecl(ClassHeader p1, ListFieldDeclaration p2) {
        classheader_ = p1;
        listfielddeclaration_ = p2;
    }

    public <R, A> R accept(Latte.Absyn.TopDef.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ClassDecl) {
            Latte.Absyn.ClassDecl x = (Latte.Absyn.ClassDecl) o;
            return this.classheader_.equals(x.classheader_) && this.listfielddeclaration_.equals(x.listfielddeclaration_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.classheader_.hashCode()) + this.listfielddeclaration_.hashCode();
    }


}
