package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class Decl extends Stmt {
    public final Type type_;
    public final ListItem listitem_;
    public int line_num, col_num, offset;

    public Decl(Type p1, ListItem p2) {
        type_ = p1;
        listitem_ = p2;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Decl) {
            Decl x = (Decl) o;
            return this.type_.equals(x.type_) && this.listitem_.equals(x.listitem_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.type_.hashCode()) + this.listitem_.hashCode();
    }

    public <T> T match(Function<Empty, T> empty,
                       Function<BStmt, T> bStmt,
                       Function<Decl, T> decl,
                       Function<Ass, T> ass,
                       Function<Incr, T> incr,
                       Function<Decr, T> decr,
                       Function<Ret, T> ret,
                       Function<VRet, T> vRet,
                       Function<Cond, T> cond,
                       Function<CondElse, T> condElse,
                       Function<While, T> sWhile,
                       Function<SExp, T> sExp) {
        return decl.apply(this);
    }
}
