package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class EAdd extends Latte.Absyn.Expr {
    public final Latte.Absyn.Expr expr_1, expr_2;
    public final Latte.Absyn.AddOp addop_;

    public EAdd(Latte.Absyn.Expr p1, Latte.Absyn.AddOp p2, Latte.Absyn.Expr p3) {
        expr_1 = p1;
        addop_ = p2;
        expr_2 = p3;
    }

    public <R, A> R accept(Latte.Absyn.Expr.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.EAdd) {
            Latte.Absyn.EAdd x = (Latte.Absyn.EAdd) o;
            return this.expr_1.equals(x.expr_1) && this.addop_.equals(x.addop_) && this.expr_2.equals(x.expr_2);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (37 * (this.expr_1.hashCode()) + this.addop_.hashCode()) + this.expr_2.hashCode();
    }

    public <T> T match(Function<Latte.Absyn.EVar, T> eVar,
                       Function<Latte.Absyn.ELitInt, T> eLitInt,
                       Function<Latte.Absyn.ELitTrue, T> eLitTrue,
                       Function<Latte.Absyn.ELitFalse, T> eLitFalse,
                       Function<Latte.Absyn.EThis, T> eThis,
                       Function<Latte.Absyn.ENull, T> eNull,
                       Function<Latte.Absyn.EApp, T> eApp,
                       Function<Latte.Absyn.EString, T> eString,
                       Function<Latte.Absyn.EConstr, T> eConstr,
                       Function<Latte.Absyn.EArrConstr, T> eArrConstr,
                       Function<Latte.Absyn.ENDArrAcc, T> eNDArrAcc,
                       Function<Latte.Absyn.FieldAcc, T> fieldAcc,
                       Function<Latte.Absyn.MethodCall, T> methodCall,
                       Function<Latte.Absyn.Neg, T> neg,
                       Function<Latte.Absyn.Not, T> not,
                       Function<Latte.Absyn.EMul, T> eMul,
                       Function<Latte.Absyn.EAdd, T> eAdd,
                       Function<Latte.Absyn.ERel, T> eRel,
                       Function<Latte.Absyn.EAnd, T> eAnd,
                       Function<Latte.Absyn.EOr, T> eOr) {
        return eAdd.apply(this);
    }
}
