package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Definitions.TypeDefinition;

import java.util.function.Function;

public class EAdd extends Expr implements Positioned {

    @Override
    public String getPosition() {
        return "(" + line_num + ", " + col_num + ")";
    }


    public final Expr expr_1, expr_2;
    public final AddOp addop_;
    public int line_num, col_num, offset;
    public TypeDefinition type;

    public EAdd(Expr p1, AddOp p2, Expr p3) {
        expr_1 = p1;
        addop_ = p2;
        expr_2 = p3;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof EAdd) {
            EAdd x = (EAdd) o;
            return this.expr_1.equals(x.expr_1) && this.addop_.equals(x.addop_) && this.expr_2.equals(x.expr_2);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (37 * (this.expr_1.hashCode()) + this.addop_.hashCode()) + this.expr_2.hashCode();
    }

    public <T> T match(Function<EVar, T> eVar, Function<ELitInt, T> eLitInt, Function<ELitTrue, T> eLitTrue, Function<ELitFalse, T> eLitFalse, Function<EThis, T> eThis, Function<ENull, T> eNull, Function<EApp, T> eApp, Function<EString, T> eString, Function<EConstr, T> eConstr, Function<EArrConstr, T> eArrConstr, Function<ENDArrAcc, T> eNDArrAcc, Function<Neg, T> neg, Function<Not, T> not, Function<EMul, T> eMul, Function<EAdd, T> eAdd, Function<ERel, T> eRel, Function<EAnd, T> eAnd, Function<EOr, T> eOr, Function<EObjAcc, T> eObjAcc, Function<ECast, T> eCast) {
        return eAdd.apply(this);
    }
}
