package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class EBracket extends EmptyBracket {
    public int line_num, col_num, offset;

    public EBracket() {
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof EBracket) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

    public <T> T match(Function<EBracket, T> eBracket) {
        return eBracket.apply(this);
    }


}
