package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class EBracket extends Latte.Absyn.EmptyBracket {
    public EBracket() {
    }

    public <R, A> R accept(Latte.Absyn.EmptyBracket.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.EBracket) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }


    public <T> T match(Function<Latte.Absyn.EBracket, T> eBracket) {
        return eBracket.apply(this);
    }


}
