package Latte.Absyn; // Java Package generated by the BNF Converter.

public class ECast  extends Expr {
  public final TypeName typename_;
  public final Expr expr_;
  public int line_num, col_num, offset;
  public ECast(TypeName p1, Expr p2) { typename_ = p1; expr_ = p2; }

  public <R,A> R accept(Latte.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.ECast) {
      Latte.Absyn.ECast x = (Latte.Absyn.ECast)o;
      return this.typename_.equals(x.typename_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.typename_.hashCode())+this.expr_.hashCode();
  }


}
