package Latte.Absyn; // Java Package generated by the BNF Converter.

public class EImpl  extends Implements {
  public int line_num, col_num, offset;
  public EImpl() { }

  public <R,A> R accept(Latte.Absyn.Implements.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.EImpl) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
