package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class EmptyMBody extends Latte.Absyn.MethodBody {
    public EmptyMBody() {
    }

    public <R, A> R accept(Latte.Absyn.MethodBody.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.EmptyMBody) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

    public <T> T match(Function<Latte.Absyn.EmptyMBody, T> emptyMBody,
                       Function<Latte.Absyn.MBody, T> mBody) {
        return emptyMBody.apply(this);
    }


}
