package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class EmptyBracket implements java.io.Serializable {
    public abstract <T> T match(Function<EBracket, T> eBracket);

}
