package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class EmptyMBody extends MethodBody implements Positioned {

    @Override
    public String getPosition() {
        return "(" + line_num + ", " + col_num + ")";
    }


    public int line_num, col_num, offset;

    public EmptyMBody() {
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof EmptyMBody) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

    public <T> T match(Function<EmptyMBody, T> emptyMBody,
                       Function<MBody, T> mBody) {
        return emptyMBody.apply(this);
    }
}
