package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class EObjAcc extends Expr {
    public final Expr expr_;
    public final ObjAcc objacc_;
    public int line_num, col_num, offset;

    public EObjAcc(Expr p1, ObjAcc p2) {
        expr_ = p1;
        objacc_ = p2;
    }


    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.EObjAcc) {
            Latte.Absyn.EObjAcc x = (Latte.Absyn.EObjAcc) o;
            return this.expr_.equals(x.expr_) && this.objacc_.equals(x.objacc_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.expr_.hashCode()) + this.objacc_.hashCode();
    }

    public <T> T match(Function<EVar, T> eVar, Function<ELitInt, T> eLitInt, Function<ELitTrue, T> eLitTrue, Function<ELitFalse, T> eLitFalse, Function<EThis, T> eThis, Function<ENull, T> eNull, Function<EApp, T> eApp, Function<EString, T> eString, Function<EConstr, T> eConstr, Function<EArrConstr, T> eArrConstr, Function<ENDArrAcc, T> eNDArrAcc, Function<Neg, T> neg, Function<Not, T> not, Function<EMul, T> eMul, Function<EAdd, T> eAdd, Function<ERel, T> eRel, Function<EAnd, T> eAnd, Function<EOr, T> eOr, Function<EObjAcc, T> eObjAcc, Function<ECast, T> eCast) {
        return eObjAcc.apply(this);
    }
}
