package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class FieldDeclaration implements java.io.Serializable {
    public abstract <R, A> R accept(FieldDeclaration.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.Dvar p, A arg);

        public R visit(Latte.Absyn.Dmth p, A arg);

    }

    public abstract <T> T match(Function<Latte.Absyn.Dvar, T> dVar,
                                Function<Latte.Absyn.Dmth, T> dMth);

}
