package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class FieldLhs extends Lhs {
  public final Expr expr_;
  public final String ident_;
  public int line_num, col_num, offset;
  public FieldLhs(Expr p1, String p2) { expr_ = p1; ident_ = p2; }


  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.FieldLhs) {
      Latte.Absyn.FieldLhs x = (Latte.Absyn.FieldLhs)o;
      return this.expr_.equals(x.expr_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.ident_.hashCode();
  }

  public <T> T match(Function<VariableRawLhs, T> variableRawLhs,
                     Function<ArrElemLhs, T> arrElemLhs,
                     Function<FieldLhs, T> fieldLhs) {
      return fieldLhs.apply(this);
  }

}
