package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ForArr  extends Stmt {
  public final BasicType basictype_;
  public final String ident_;
  public final Expr expr_;
  public final Stmt stmt_;
  public int line_num, col_num, offset;
  public ForArr(BasicType p1, String p2, Expr p3, Stmt p4) { basictype_ = p1; ident_ = p2; expr_ = p3; stmt_ = p4; }


  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.ForArr) {
      Latte.Absyn.ForArr x = (Latte.Absyn.ForArr)o;
      return this.basictype_.equals(x.basictype_) && this.ident_.equals(x.ident_) && this.expr_.equals(x.expr_) && this.stmt_.equals(x.stmt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.basictype_.hashCode())+this.ident_.hashCode())+this.expr_.hashCode())+this.stmt_.hashCode();
  }

  public <T> T match(Function<Empty, T> empty,
                     Function<BStmt, T> bStmt,
                     Function<Decl, T> decl,
                     Function<Ass, T> ass,
                     Function<Incr, T> incr,
                     Function<Decr, T> decr,
                     Function<Ret, T> ret,
                     Function<VRet, T> vRet,
                     Function<Cond, T> cond,
                     Function<CondElse, T> condElse,
                     Function<While, T> sWhile,
                     Function<SExp, T> sExp,
                     Function<ForArr, T> forArr) {
    return forArr.apply(this);
  }
}
