package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Implements implements java.io.Serializable {

    public abstract <T> T match(Function<InterImpl, T> interImpl,
                                Function<EImpl, T> emptyImpl);

}
