package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Lhs implements java.io.Serializable {
  public abstract <R,A> R accept(Lhs.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.VariableRawLhs p, A arg);
    public R visit(Latte.Absyn.ArrElemLhs p, A arg);
    public R visit(Latte.Absyn.FieldLhs p, A arg);

  }

}
