package Latte.Absyn; // Java Package generated by the BNF Converter.

import Latte.Backend.Definitions.Binding;

import java.util.function.Function;

public abstract class Lhs implements java.io.Serializable {
    public Binding binding;

  public abstract <T> T match(Function<VariableRawLhs, T> variableRawLhs,
                              Function<ArrElemLhs, T> arrElemLhs,
                              Function<FieldLhs, T> fieldLhs);

}
