package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class MBody extends MethodBody {
    public final Block block_;
    public int line_num, col_num, offset;

    public MBody(Block p1) {
        block_ = p1;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof MBody) {
            MBody x = (MBody) o;
            return this.block_.equals(x.block_);
        }
        return false;
    }

    public int hashCode() {
        return this.block_.hashCode();
    }

    public <T> T match(Function<EmptyMBody, T> emptyMBody,
                       Function<MBody, T> mBody) {
        return mBody.apply(this);
    }
}
