package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class MBody extends Latte.Absyn.MethodBody {
    public final Latte.Absyn.Block block_;

    public MBody(Latte.Absyn.Block p1) {
        block_ = p1;
    }

    public <R, A> R accept(Latte.Absyn.MethodBody.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.MBody) {
            Latte.Absyn.MBody x = (Latte.Absyn.MBody) o;
            return this.block_.equals(x.block_);
        }
        return false;
    }

    public int hashCode() {
        return this.block_.hashCode();
    }

    public <T> T match(Function<Latte.Absyn.EmptyMBody, T> emptyMBody,
                       Function<Latte.Absyn.MBody, T> mBody) {
        return mBody.apply(this);
    }
}
