package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class MethodBody implements java.io.Serializable {
    public abstract <R, A> R accept(MethodBody.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.EmptyMBody p, A arg);

        public R visit(Latte.Absyn.MBody p, A arg);

    }


    public abstract <T> T match(Function<Latte.Absyn.EmptyMBody, T> emptyMBody,
                                Function<Latte.Absyn.MBody, T> mBody);

}
