package Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Modifier implements java.io.Serializable {

    public abstract <T> T match(Function<Mfinal, T> mFinal,
                                Function<Mpublic, T> mPublic,
                                Function<Mprivate, T> mPrivate,
                                Function<Mstatic, T> mStatic,
                                Function<MEmpty, T> mEmpty);

}
