package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Modifier implements java.io.Serializable {
    public abstract <R, A> R accept(Modifier.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.Mfinal p, A arg);

        public R visit(Latte.Absyn.Mpublic p, A arg);

        public R visit(Latte.Absyn.Mprivate p, A arg);

        public R visit(Latte.Absyn.Mstatic p, A arg);

        public R visit(Latte.Absyn.MEmpty p, A arg);

    }

}
