package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Modifier implements java.io.Serializable {
    public abstract <R, A> R accept(Modifier.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.Mfinal p, A arg);

        public R visit(Latte.Absyn.Mpublic p, A arg);

        public R visit(Latte.Absyn.Mprivate p, A arg);

        public R visit(Latte.Absyn.Mstatic p, A arg);

        public R visit(Latte.Absyn.MEmpty p, A arg);

    }

    public abstract <T> T match(Function<Latte.Absyn.Mfinal, T> mFinal,
                               Function<Latte.Absyn.Mpublic, T> mPublic,
                               Function<Latte.Absyn.Mprivate, T> mPrivate,
                               Function<Latte.Absyn.Mstatic, T> mStatic,
                               Function<Latte.Absyn.MEmpty, T> mEmpty);

}
