package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class Mpublic extends Latte.Absyn.Modifier {
    public Mpublic() {
    }

    public <R, A> R accept(Latte.Absyn.Modifier.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.Mpublic) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

    public <T> T match(Function<Latte.Absyn.Mfinal, T> mFinal,
                       Function<Latte.Absyn.Mpublic, T> mPublic,
                       Function<Latte.Absyn.Mprivate, T> mPrivate,
                       Function<Latte.Absyn.Mstatic, T> mStatic,
                       Function<Latte.Absyn.MEmpty, T> mEmpty) {
        return mPublic.apply(this);
    }
}
