package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class MulOp implements java.io.Serializable {
    public abstract <R, A> R accept(MulOp.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.Times p, A arg);

        public R visit(Latte.Absyn.Div p, A arg);

        public R visit(Latte.Absyn.Mod p, A arg);

    }

    public abstract  <T> T match(Function<Latte.Absyn.Times, T> times,
                                Function<Latte.Absyn.Div, T> div,
                                Function<Latte.Absyn.Mod, T> mod);



}
