package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class ObjAcc implements java.io.Serializable {
    public abstract <T> T match(Function<ObjFieldAcc, T> objFieldAcc,
                                Function<ObjMethAcc, T> objMethAcc);

}
