package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ObjFieldAcc extends ObjAcc {
    public final String ident_;
    public int line_num, col_num, offset;

    public ObjFieldAcc(String p1) {
        ident_ = p1;
    }


    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ObjFieldAcc) {
            Latte.Absyn.ObjFieldAcc x = (Latte.Absyn.ObjFieldAcc) o;
            return this.ident_.equals(x.ident_);
        }
        return false;
    }

    public int hashCode() {
        return this.ident_.hashCode();
    }

    public <T> T match(Function<ObjFieldAcc, T> objFieldAcc,
                       Function<ObjMethAcc, T> objMethAcc) {
        return objFieldAcc.apply(this);
    }
}
