package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class Plus extends Latte.Absyn.AddOp {
    public Plus() {
    }

    public <R, A> R accept(Latte.Absyn.AddOp.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.Plus) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }


    public <T> T match(Function<Latte.Absyn.Plus, T> plus,
                       Function<Latte.Absyn.Minus, T> minus) {
        return plus.apply(this);
    }


}
