package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ProgramTD extends Latte.Absyn.Program {
    public final Latte.Absyn.ListTopDef listtopdef_;

    public ProgramTD(Latte.Absyn.ListTopDef p1) {
        listtopdef_ = p1;
    }

    public <R, A> R accept(Latte.Absyn.Program.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.ProgramTD) {
            Latte.Absyn.ProgramTD x = (Latte.Absyn.ProgramTD) o;
            return this.listtopdef_.equals(x.listtopdef_);
        }
        return false;
    }

    public int hashCode() {
        return this.listtopdef_.hashCode();
    }


    public <T> T match(Function<Latte.Absyn.ProgramTD, T> td) {
        return td.apply(this);
    }
}
