package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Program implements java.io.Serializable {
    public abstract <R, A> R accept(Program.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.ProgramTD p, A arg);

    }


    public abstract  <T> T match(Function<Latte.Absyn.ProgramTD, T> td);
}
