package Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class RelOp implements java.io.Serializable {

    public abstract <T> T match(Function<LTH, T> lth,
                                Function<LE, T> le,
                                Function<GTH, T> gth,
                                Function<GE, T> ge,
                                Function<EQU, T> equ,
                                Function<NE, T> ne);
}
