package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class RelOp implements java.io.Serializable {
    public abstract <R, A> R accept(RelOp.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.LTH p, A arg);

        public R visit(Latte.Absyn.LE p, A arg);

        public R visit(Latte.Absyn.GTH p, A arg);

        public R visit(Latte.Absyn.GE p, A arg);

        public R visit(Latte.Absyn.EQU p, A arg);

        public R visit(Latte.Absyn.NE p, A arg);

    }

}
