package Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class Ret extends Stmt {
    public final Expr expr_;
    public int line_num, col_num, offset;

    public Ret(Expr p1) {
        expr_ = p1;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Ret) {
            Ret x = (Ret) o;
            return this.expr_.equals(x.expr_);
        }
        return false;
    }

    public int hashCode() {
        return this.expr_.hashCode();
    }

    public <T> T match(Function<Empty, T> empty,
                       Function<BStmt, T> bStmt,
                       Function<Decl, T> decl,
                       Function<Ass, T> ass,
                       Function<Incr, T> incr,
                       Function<Decr, T> decr,
                       Function<Ret, T> ret,
                       Function<VRet, T> vRet,
                       Function<Cond, T> cond,
                       Function<CondElse, T> condElse,
                       Function<While, T> sWhile,
                       Function<SExp, T> sExp) {
        return ret.apply(this);
    }


}
