package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class SBracket extends SizeBracket {
    public final Expr expr_;
    public int line_num, col_num, offset;

    public SBracket(Expr p1) {
        expr_ = p1;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof SBracket) {
            SBracket x = (SBracket) o;
            return this.expr_.equals(x.expr_);
        }
        return false;
    }

    public int hashCode() {
        return this.expr_.hashCode();
    }


    public <T> T match(Function<SBracket, T> sBracket) {
        return sBracket.apply(this);
    }

}
