package Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class SizeBracket implements java.io.Serializable {

    public abstract  <T> T match(Function<SBracket, T> sBracket);
}
