package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class SizeBracket implements java.io.Serializable {
    public abstract <R, A> R accept(SizeBracket.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.SBracket p, A arg);

    }

}
