package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class Times extends Latte.Absyn.MulOp {
    public Times() {
    }

    public <R, A> R accept(Latte.Absyn.MulOp.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.Times) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

    public <T> T match(Function<Latte.Absyn.Times, T> times,
                     Function<Latte.Absyn.Div, T> div,
                     Function<Latte.Absyn.Mod, T> mod) {
        return times.apply(this);
    }
}
