package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class TopDef implements java.io.Serializable {
    public abstract <R, A> R accept(TopDef.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.FnDef p, A arg);

        public R visit(Latte.Absyn.ClassDecl p, A arg);

    }

}
