package Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class TopDef implements java.io.Serializable {

    public abstract <T> T match(Function<FnDef, T> fnDef,
                                Function<ClassDecl, T> classDecl);

}
