package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Type implements java.io.Serializable {
    public abstract <R, A> R accept(Type.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.ArrayType p, A arg);

        public R visit(Latte.Absyn.TypeNameS p, A arg);

    }

    public abstract <T> T match(Function<Latte.Absyn.ArrayType, T> arrayType,
                                Function<Latte.Absyn.TypeNameS, T> typeNameS);

}
