package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class TypeNameS extends Latte.Absyn.Type {
    public final Latte.Absyn.TypeName typename_;

    public TypeNameS(Latte.Absyn.TypeName p1) {
        typename_ = p1;
    }

    public <R, A> R accept(Latte.Absyn.Type.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.TypeNameS) {
            Latte.Absyn.TypeNameS x = (Latte.Absyn.TypeNameS) o;
            return this.typename_.equals(x.typename_);
        }
        return false;
    }

    public int hashCode() {
        return this.typename_.hashCode();
    }

    public <T> T match(Function<Latte.Absyn.ArrayType, T> arrayType,
                       Function<Latte.Absyn.TypeNameS, T> typeNameS) {
        return typeNameS.apply(this);
    }
}
