package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class TypeName implements java.io.Serializable {
    public abstract <R, A> R accept(TypeName.Visitor<R, A> v, A arg);

    public interface Visitor<R, A> {
        public R visit(Latte.Absyn.BuiltIn p, A arg);

        public R visit(Latte.Absyn.ClassName p, A arg);

    }

}
