package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Type implements java.io.Serializable {
    public abstract <T> T match(Function<ArrayType, T> arrayType,
                                Function<TypeNameS, T> typeNameS);
}
