package Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class TypeNameS extends Type {
    public final TypeName typename_;
    public int line_num, col_num, offset;

    public TypeNameS(TypeName p1) {
        typename_ = p1;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof TypeNameS) {
            TypeNameS x = (TypeNameS) o;
            return this.typename_.equals(x.typename_);
        }
        return false;
    }

    public int hashCode() {
        return this.typename_.hashCode();
    }

    public <T> T match(Function<ArrayType, T> arrayType,
                       Function<TypeNameS, T> typeNameS) {
        return typeNameS.apply(this);
    }
}
