package Latte.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class Void extends Latte.Absyn.BasicType {
    public Void() {
    }

    public <R, A> R accept(Latte.Absyn.BasicType.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Latte.Absyn.Void) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

    public <T> T match(Function<Latte.Absyn.Int, T> intT,
                       Function<Latte.Absyn.Str, T> strT,
                       Function<Latte.Absyn.Bool, T> boolT,
                       Function<Latte.Absyn.Void, T> voidT) {
        return voidT.apply(this);
    }

}
