package Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class VRet extends Stmt {
    public int line_num, col_num, offset;

    public VRet() {
    }


    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof VRet) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

    public <T> T match(Function<Empty, T> empty,
                       Function<BStmt, T> bStmt,
                       Function<Decl, T> decl,
                       Function<Ass, T> ass,
                       Function<Incr, T> incr,
                       Function<Decr, T> decr,
                       Function<Ret, T> ret,
                       Function<VRet, T> vRet,
                       Function<Cond, T> cond,
                       Function<CondElse, T> condElse,
                       Function<While, T> sWhile,
                       Function<SExp, T> sExp) {
        return vRet.apply(this);
    }
}
