// This JLex file was machine-generated by the BNF converter
package Latte;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  final int unknown = -1;
  ComplexSymbolFactory.Location left = new ComplexSymbolFactory.Location(unknown, unknown);
  ComplexSymbolFactory cf = new ComplexSymbolFactory();
  public SymbolFactory getSymbolFactory() { return cf; }
  int yycolumn = unknown - 1;
  public int line_num() { return (yyline+1); }
  public ComplexSymbolFactory.Location left_loc() {
    return new ComplexSymbolFactory.Location(yyline+1, yycolumn+1, yychar);
  }
  public ComplexSymbolFactory.Location right_loc() {
    ComplexSymbolFactory.Location left = left_loc();
  return new ComplexSymbolFactory.Location(left.getLine(), left.getColumn()+yylength(), left.getOffset()+yylength());
  }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yychar;
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yychar = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		81,
		84,
		84,
		84,
		86,
		88
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yychar = yychar
			+ yy_buffer_index - yy_buffer_start;
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NO_ANCHOR,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NOT_ACCEPT,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NOT_ACCEPT,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NOT_ACCEPT,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NOT_ACCEPT,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NOT_ACCEPT,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NOT_ACCEPT,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NO_ANCHOR,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR,
		/* 111 */ YY_NO_ANCHOR,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NO_ANCHOR,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NO_ANCHOR,
		/* 123 */ YY_NO_ANCHOR,
		/* 124 */ YY_NO_ANCHOR,
		/* 125 */ YY_NO_ANCHOR,
		/* 126 */ YY_NO_ANCHOR,
		/* 127 */ YY_NO_ANCHOR,
		/* 128 */ YY_NO_ANCHOR,
		/* 129 */ YY_NO_ANCHOR,
		/* 130 */ YY_NO_ANCHOR,
		/* 131 */ YY_NO_ANCHOR,
		/* 132 */ YY_NO_ANCHOR,
		/* 133 */ YY_NO_ANCHOR,
		/* 134 */ YY_NO_ANCHOR,
		/* 135 */ YY_NO_ANCHOR,
		/* 136 */ YY_NO_ANCHOR,
		/* 137 */ YY_NO_ANCHOR,
		/* 138 */ YY_NO_ANCHOR,
		/* 139 */ YY_NO_ANCHOR,
		/* 140 */ YY_NO_ANCHOR,
		/* 141 */ YY_NO_ANCHOR,
		/* 142 */ YY_NO_ANCHOR,
		/* 143 */ YY_NO_ANCHOR,
		/* 144 */ YY_NO_ANCHOR,
		/* 145 */ YY_NO_ANCHOR,
		/* 146 */ YY_NO_ANCHOR,
		/* 147 */ YY_NO_ANCHOR,
		/* 148 */ YY_NO_ANCHOR,
		/* 149 */ YY_NO_ANCHOR,
		/* 150 */ YY_NO_ANCHOR,
		/* 151 */ YY_NO_ANCHOR,
		/* 152 */ YY_NO_ANCHOR,
		/* 153 */ YY_NO_ANCHOR,
		/* 154 */ YY_NO_ANCHOR,
		/* 155 */ YY_NO_ANCHOR,
		/* 156 */ YY_NO_ANCHOR,
		/* 157 */ YY_NO_ANCHOR,
		/* 158 */ YY_NO_ANCHOR,
		/* 159 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"45:9,52,44,45,52,43,45:18,52,14,46,42,45,19,15,51,1,2,17,8,5,9,13,18,48:10," +
"10,6,20,7,21,45:2,49:26,11,47,12,45,51,45,26,22,28,40,25,30,39,41,31,50:2,2" +
"4,33,27,23,34,50,32,29,35,37,38,36,50:3,3,16,4,45:66,49:23,45,49:7,50:24,45" +
",50:8,45:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,160,
"0,1:7,2,3,4,1,5,1:2,6,7,1,8,1,9,10,11,1:2,12,1:10,13,1:2,13:2,14,13:17,1:4," +
"15,1:5,16,1:2,17,18,19,20,1:2,21:2,22,23,1,24,25,26,27,28,29,30,31,32,33,34" +
",35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59" +
",60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84" +
",85,86,87,88,89,90,91,92,13,93,94,95,96,97,98,13")[0];

	private int yy_nxt[][] = unpackFromString(99,53,
"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,73,17,18,19,20,21,22,159:2,124,159,1" +
"05,140,125,106,74,149,159,150,126,141,159,127,159:3,79,23:2,82,24,82,25,159" +
":2,82,23,-1:60,26,-1:53,27,-1:53,28,-1:55,29,-1:47,30,-1:60,31,-1:54,33,72," +
"-1:41,34,-1:52,35,-1:67,159,151,159:18,-1:6,152:2,159,152,-1:49,25,-1:26,15" +
"9:20,-1:6,152:2,159,152,-1:23,159:3,156,159:16,-1:6,152:2,159,152,-1:45,76," +
"-1:52,77,-1:9,72:43,38,72:8,-1:16,32,-1:58,159:5,85,159:2,36,159:2,153,159:" +
"8,-1:6,152:2,159,152,-1:19,61,-1:35,78:43,37,78:8,-1:22,159:14,39,159:5,-1:" +
"6,152:2,159,152,-1,1,59:16,75,59:25,-1,60,59:8,-1:22,159:10,40,159:9,-1:6,1" +
"52:2,159,152,-1,1,82:42,-1:2,82:8,-1:22,159:13,41,159:6,-1:6,152:2,159,152," +
"-1,1,62:42,63,76,62,64,65,62:5,-1:22,159:3,42,159:16,-1:6,152:2,159,152,-1," +
"1,66:26,67,66:7,68,66:7,69,77,66,70,71,66:5,-1:22,159:2,43,159:17,-1:6,152:" +
"2,159,152,-1:23,159:8,44,159:11,-1:6,152:2,159,152,-1:23,159:3,45,159:16,-1" +
":6,152:2,159,152,-1:23,159:18,46,159,-1:6,152:2,159,152,-1:23,159:7,47,159:" +
"12,-1:6,152:2,159,152,-1:23,159:3,48,159:16,-1:6,152:2,159,152,-1:23,159:2," +
"49,159:17,-1:6,152:2,159,152,-1:23,159:3,50,159:16,-1:6,152:2,159,152,-1:23" +
",159:6,51,159:13,-1:6,152:2,159,152,-1:23,159:17,52,159:2,-1:6,152:2,159,15" +
"2,-1:23,159:5,53,159:14,-1:6,152:2,159,152,-1:23,159:6,54,159:13,-1:6,152:2" +
",159,152,-1:23,159:5,55,159:14,-1:6,152:2,159,152,-1:23,159:3,56,159:16,-1:" +
"6,152:2,159,152,-1:23,159:3,57,159:16,-1:6,152:2,159,152,-1:23,159:7,58,159" +
":12,-1:6,152:2,159,152,-1:23,159:3,80,159:11,108,159:4,-1:6,152:2,159,152,-" +
"1:23,159,83,159:2,129,159:4,130,159:10,-1:6,152:2,159,152,-1:23,159:7,87,15" +
"9:12,-1:6,152:2,159,152,-1:23,159:2,89,159:17,-1:6,152:2,159,152,-1:23,159:" +
"2,90,159:17,-1:6,152:2,159,152,-1:23,159:15,91,159:4,-1:6,152:2,159,152,-1:" +
"23,159:9,92,159:10,-1:6,152:2,159,152,-1:23,159:7,93,159:12,-1:6,152:2,159," +
"152,-1:23,159:7,94,159:12,-1:6,152:2,159,152,-1:23,159:4,95,159:15,-1:6,152" +
":2,159,152,-1:23,159:2,96,159:17,-1:6,152:2,159,152,-1:23,159:9,97,159:10,-" +
"1:6,152:2,159,152,-1:23,159:5,98,159:14,-1:6,152:2,159,152,-1:23,159:10,99," +
"159:9,-1:6,152:2,159,152,-1:23,159:9,100,159:10,-1:6,152:2,159,152,-1:23,15" +
"9:4,101,159:15,-1:6,152:2,159,152,-1:23,159:13,102,159:6,-1:6,152:2,159,152" +
",-1:23,159:6,103,159:13,-1:6,152:2,159,152,-1:23,159:13,104,159:6,-1:6,152:" +
"2,159,152,-1:23,159:2,107,159:17,-1:6,152:2,159,152,-1:23,159:3,109,159:9,1" +
"42,159:6,-1:6,152:2,159,152,-1:23,159:10,110,159:9,-1:6,152:2,159,152,-1:23" +
",159,111,159:18,-1:6,152:2,159,152,-1:23,159:4,112,159:15,-1:6,152:2,159,15" +
"2,-1:23,159:2,113,159:17,-1:6,152:2,159,152,-1:23,159:5,114,159:14,-1:6,152" +
":2,159,152,-1:23,159:9,115,159:10,-1:6,152:2,159,152,-1:23,159:13,116,159:6" +
",-1:6,152:2,159,152,-1:23,159:9,117,159:10,-1:6,152:2,159,152,-1:23,159:15," +
"118,159:4,-1:6,152:2,159,152,-1:23,159:2,119,159:17,-1:6,152:2,159,152,-1:2" +
"3,159:3,120,159:16,-1:6,152:2,159,152,-1:23,159:4,121,159:15,-1:6,152:2,159" +
",152,-1:23,159:4,122,159:15,-1:6,152:2,159,152,-1:23,159:5,123,159:14,-1:6," +
"152:2,159,152,-1:23,159:2,128,159:17,-1:6,152:2,159,152,-1:23,159:19,131,-1" +
":6,152:2,159,152,-1:23,159:4,132,159:5,133,159:9,-1:6,152:2,159,152,-1:23,1" +
"59:13,134,159:6,-1:6,152:2,159,152,-1:23,135,159:19,-1:6,152:2,159,152,-1:2" +
"3,159:2,136,159:17,-1:6,152:2,159,152,-1:23,159:16,137,159:3,-1:6,152:2,159" +
",152,-1:23,159:8,138,159:11,-1:6,152:2,159,152,-1:23,159:3,139,159:16,-1:6," +
"152:2,159,152,-1:23,159:3,143,159:16,-1:6,152:2,159,152,-1:23,159:10,154,15" +
"9:4,144,159:4,-1:6,152:2,159,152,-1:23,159,145,159:18,-1:6,152:2,159,152,-1" +
":23,159:12,155,159:7,-1:6,152:2,159,152,-1:23,159:9,146,159:10,-1:6,152:2,1" +
"59,152,-1:23,159:2,157,159:17,-1:6,152:2,159,152,-1:23,159:10,147,159:9,-1:" +
"6,152:2,159,152,-1:23,159:3,158,159:16,-1:6,152:2,159,152,-1:23,159:11,148," +
"159:8,-1:6,152:2,159,152,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {

  return cf.newSymbol("EOF", sym.EOF, left_loc(), left_loc());
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return cf.newSymbol("", sym._SYMB_0, left_loc(), right_loc()); }
					case -3:
						break;
					case 3:
						{ return cf.newSymbol("", sym._SYMB_1, left_loc(), right_loc()); }
					case -4:
						break;
					case 4:
						{ return cf.newSymbol("", sym._SYMB_2, left_loc(), right_loc()); }
					case -5:
						break;
					case 5:
						{ return cf.newSymbol("", sym._SYMB_3, left_loc(), right_loc()); }
					case -6:
						break;
					case 6:
						{ return cf.newSymbol("", sym._SYMB_4, left_loc(), right_loc()); }
					case -7:
						break;
					case 7:
						{ return cf.newSymbol("", sym._SYMB_5, left_loc(), right_loc()); }
					case -8:
						break;
					case 8:
						{ return cf.newSymbol("", sym._SYMB_6, left_loc(), right_loc()); }
					case -9:
						break;
					case 9:
						{ return cf.newSymbol("", sym._SYMB_18, left_loc(), right_loc()); }
					case -10:
						break;
					case 10:
						{ return cf.newSymbol("", sym._SYMB_14, left_loc(), right_loc()); }
					case -11:
						break;
					case 11:
						{ return cf.newSymbol("", sym._SYMB_9, left_loc(), right_loc()); }
					case -12:
						break;
					case 12:
						{ return cf.newSymbol("", sym._SYMB_10, left_loc(), right_loc()); }
					case -13:
						break;
					case 13:
						{ return cf.newSymbol("", sym._SYMB_11, left_loc(), right_loc()); }
					case -14:
						break;
					case 14:
						{ return cf.newSymbol("", sym._SYMB_12, left_loc(), right_loc()); }
					case -15:
						break;
					case 15:
						{ return cf.newSymbol("", sym._SYMB_15, left_loc(), right_loc()); }
					case -16:
						break;
					case 16:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -17:
						break;
					case 17:
						{ return cf.newSymbol("", sym._SYMB_19, left_loc(), right_loc()); }
					case -18:
						break;
					case 18:
						{ return cf.newSymbol("", sym._SYMB_20, left_loc(), right_loc()); }
					case -19:
						break;
					case 19:
						{ return cf.newSymbol("", sym._SYMB_21, left_loc(), right_loc()); }
					case -20:
						break;
					case 20:
						{ return cf.newSymbol("", sym._SYMB_22, left_loc(), right_loc()); }
					case -21:
						break;
					case 21:
						{ return cf.newSymbol("", sym._SYMB_24, left_loc(), right_loc()); }
					case -22:
						break;
					case 22:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -23:
						break;
					case 23:
						{ /* ignore white space. */ }
					case -24:
						break;
					case 24:
						{ left = left_loc(); yybegin(STRING); }
					case -25:
						break;
					case 25:
						{ return cf.newSymbol("", sym._INTEGER_, left_loc(), right_loc(), new Integer(yytext())); }
					case -26:
						break;
					case 26:
						{ return cf.newSymbol("", sym._SYMB_26, left_loc(), right_loc()); }
					case -27:
						break;
					case 27:
						{ return cf.newSymbol("", sym._SYMB_7, left_loc(), right_loc()); }
					case -28:
						break;
					case 28:
						{ return cf.newSymbol("", sym._SYMB_8, left_loc(), right_loc()); }
					case -29:
						break;
					case 29:
						{ return cf.newSymbol("", sym._SYMB_13, left_loc(), right_loc()); }
					case -30:
						break;
					case 30:
						{ return cf.newSymbol("", sym._SYMB_27, left_loc(), right_loc()); }
					case -31:
						break;
					case 31:
						{ return cf.newSymbol("", sym._SYMB_16, left_loc(), right_loc()); }
					case -32:
						break;
					case 32:
						{ return cf.newSymbol("", sym._SYMB_17, left_loc(), right_loc()); }
					case -33:
						break;
					case 33:
						{ yybegin(COMMENT); }
					case -34:
						break;
					case 34:
						{ return cf.newSymbol("", sym._SYMB_23, left_loc(), right_loc()); }
					case -35:
						break;
					case 35:
						{ return cf.newSymbol("", sym._SYMB_25, left_loc(), right_loc()); }
					case -36:
						break;
					case 36:
						{ return cf.newSymbol("", sym._SYMB_34, left_loc(), right_loc()); }
					case -37:
						break;
					case 37:
						{ /* skip */ }
					case -38:
						break;
					case 38:
						{ /* skip */ }
					case -39:
						break;
					case 39:
						{ return cf.newSymbol("", sym._SYMB_38, left_loc(), right_loc()); }
					case -40:
						break;
					case 40:
						{ return cf.newSymbol("", sym._SYMB_33, left_loc(), right_loc()); }
					case -41:
						break;
					case 41:
						{ return cf.newSymbol("", sym._SYMB_36, left_loc(), right_loc()); }
					case -42:
						break;
					case 42:
						{ return cf.newSymbol("", sym._SYMB_30, left_loc(), right_loc()); }
					case -43:
						break;
					case 43:
						{ return cf.newSymbol("", sym._SYMB_39, left_loc(), right_loc()); }
					case -44:
						break;
					case 44:
						{ return cf.newSymbol("", sym._SYMB_43, left_loc(), right_loc()); }
					case -45:
						break;
					case 45:
						{ return cf.newSymbol("", sym._SYMB_46, left_loc(), right_loc()); }
					case -46:
						break;
					case 46:
						{ return cf.newSymbol("", sym._SYMB_47, left_loc(), right_loc()); }
					case -47:
						break;
					case 47:
						{ return cf.newSymbol("", sym._SYMB_29, left_loc(), right_loc()); }
					case -48:
						break;
					case 48:
						{ return cf.newSymbol("", sym._SYMB_31, left_loc(), right_loc()); }
					case -49:
						break;
					case 49:
						{ return cf.newSymbol("", sym._SYMB_32, left_loc(), right_loc()); }
					case -50:
						break;
					case 50:
						{ return cf.newSymbol("", sym._SYMB_48, left_loc(), right_loc()); }
					case -51:
						break;
					case 51:
						{ return cf.newSymbol("", sym._SYMB_44, left_loc(), right_loc()); }
					case -52:
						break;
					case 52:
						{ return cf.newSymbol("", sym._SYMB_45, left_loc(), right_loc()); }
					case -53:
						break;
					case 53:
						{ return cf.newSymbol("", sym._SYMB_42, left_loc(), right_loc()); }
					case -54:
						break;
					case 54:
						{ return cf.newSymbol("", sym._SYMB_41, left_loc(), right_loc()); }
					case -55:
						break;
					case 55:
						{ return cf.newSymbol("", sym._SYMB_28, left_loc(), right_loc()); }
					case -56:
						break;
					case 56:
						{ return cf.newSymbol("", sym._SYMB_40, left_loc(), right_loc()); }
					case -57:
						break;
					case 57:
						{ return cf.newSymbol("", sym._SYMB_37, left_loc(), right_loc()); }
					case -58:
						break;
					case 58:
						{ return cf.newSymbol("", sym._SYMB_35, left_loc(), right_loc()); }
					case -59:
						break;
					case 59:
						{ /* skip */ }
					case -60:
						break;
					case 60:
						{ /* skip */ }
					case -61:
						break;
					case 61:
						{ yybegin(YYINITIAL); }
					case -62:
						break;
					case 62:
						{ pstring += yytext(); }
					case -63:
						break;
					case 63:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -64:
						break;
					case 64:
						{ String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return cf.newSymbol("", sym._STRING_, left, right_loc(), foo.intern()); }
					case -65:
						break;
					case 65:
						{ yybegin(ESCAPED); }
					case -66:
						break;
					case 66:
						{ pstring += yytext(); yybegin(STRING); }
					case -67:
						break;
					case 67:
						{ pstring +=  "\n"; yybegin(STRING); }
					case -68:
						break;
					case 68:
						{ pstring += "\t"; yybegin(STRING); }
					case -69:
						break;
					case 69:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -70:
						break;
					case 70:
						{ pstring += "\""; yybegin(STRING); }
					case -71:
						break;
					case 71:
						{ pstring += "\\"; yybegin(STRING); }
					case -72:
						break;
					case 73:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -73:
						break;
					case 74:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -74:
						break;
					case 75:
						{ /* skip */ }
					case -75:
						break;
					case 76:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -76:
						break;
					case 77:
						{ throw new Error("Unterminated string on line " + left.getLine() ); }
					case -77:
						break;
					case 79:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -78:
						break;
					case 80:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -79:
						break;
					case 82:
						{ throw new Error("Illegal Character <"+yytext()+"> at "+(yyline+1)); }
					case -80:
						break;
					case 83:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -81:
						break;
					case 85:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -82:
						break;
					case 87:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -83:
						break;
					case 89:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -84:
						break;
					case 90:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -85:
						break;
					case 91:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -86:
						break;
					case 92:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -87:
						break;
					case 93:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -88:
						break;
					case 94:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -89:
						break;
					case 95:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -90:
						break;
					case 96:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -91:
						break;
					case 97:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -92:
						break;
					case 98:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -93:
						break;
					case 99:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -94:
						break;
					case 100:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -95:
						break;
					case 101:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -96:
						break;
					case 102:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -97:
						break;
					case 103:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -98:
						break;
					case 104:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -99:
						break;
					case 105:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -100:
						break;
					case 106:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -101:
						break;
					case 107:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -102:
						break;
					case 108:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -103:
						break;
					case 109:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -104:
						break;
					case 110:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -105:
						break;
					case 111:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -106:
						break;
					case 112:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -107:
						break;
					case 113:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -108:
						break;
					case 114:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -109:
						break;
					case 115:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -110:
						break;
					case 116:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -111:
						break;
					case 117:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -112:
						break;
					case 118:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -113:
						break;
					case 119:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -114:
						break;
					case 120:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -115:
						break;
					case 121:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -116:
						break;
					case 122:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -117:
						break;
					case 123:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -118:
						break;
					case 124:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -119:
						break;
					case 125:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -120:
						break;
					case 126:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -121:
						break;
					case 127:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -122:
						break;
					case 128:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -123:
						break;
					case 129:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -124:
						break;
					case 130:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -125:
						break;
					case 131:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -126:
						break;
					case 132:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -127:
						break;
					case 133:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -128:
						break;
					case 134:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -129:
						break;
					case 135:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -130:
						break;
					case 136:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -131:
						break;
					case 137:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -132:
						break;
					case 138:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -133:
						break;
					case 139:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -134:
						break;
					case 140:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -135:
						break;
					case 141:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -136:
						break;
					case 142:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -137:
						break;
					case 143:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -138:
						break;
					case 144:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -139:
						break;
					case 145:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -140:
						break;
					case 146:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -141:
						break;
					case 147:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -142:
						break;
					case 148:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -143:
						break;
					case 149:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -144:
						break;
					case 150:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -145:
						break;
					case 151:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -146:
						break;
					case 152:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -147:
						break;
					case 153:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -148:
						break;
					case 154:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -149:
						break;
					case 155:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -150:
						break;
					case 156:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -151:
						break;
					case 157:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -152:
						break;
					case 158:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -153:
						break;
					case 159:
						{ return cf.newSymbol("", sym._IDENT_, left_loc(), right_loc(), yytext().intern()); }
					case -154:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
