package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ArrElemLhs extends Lhs {
    public final Expr expr_1, expr_2;
    public int line_num, col_num, offset;

    public ArrElemLhs(Expr p1, Expr p2) {
        expr_1 = p1;
        expr_2 = p2;
    }


    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof src.Absyn.ArrElemLhs) {
            src.Absyn.ArrElemLhs x = (src.Absyn.ArrElemLhs) o;
            return this.expr_1.equals(x.expr_1) && this.expr_2.equals(x.expr_2);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.expr_1.hashCode()) + this.expr_2.hashCode();
    }


    public <T> T match(Function<VariableRawLhs, T> variableRawLhs,
                       Function<ArrElemLhs, T> arrElemLhs,
                       Function<FieldLhs, T> fieldLhs) {
        return arrElemLhs.apply(this);
    }
}
