package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class BlockS extends Block implements Positioned {

    @Override
    public String getPosition() {
        return "(" + line_num + ", " + col_num + ")";
    }


    public final ListStmt liststmt_;
    public int line_num, col_num, offset;

    public BlockS(ListStmt p1) {
        liststmt_ = p1;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof BlockS) {
            BlockS x = (BlockS) o;
            return this.liststmt_.equals(x.liststmt_);
        }
        return false;
    }

    public int hashCode() {
        return this.liststmt_.hashCode();
    }

    public <T> T match(Function<BlockS, T> blockS) {
        return blockS.apply(this);
    }

}
