package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Block implements java.io.Serializable {

    public abstract <T> T match(Function<BlockS, T> blockS);

}
