package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.Objects;
import java.util.function.Function;

public class ClassDec extends ClassHeader implements Positioned {

    @Override
    public String getPosition() {
        return "(" + line_num + ", " + col_num + ")";
    }


    public final String ident_;
    public final Implements implements_;
    public int line_num, col_num, offset;

    public ClassDec(String p1, Implements p2) {
        ident_ = p1;
        implements_ = p2;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ClassDec classDec = (ClassDec) o;
        return line_num == classDec.line_num &&
                col_num == classDec.col_num &&
                offset == classDec.offset &&
                Objects.equals(ident_, classDec.ident_) &&
                Objects.equals(implements_, classDec.implements_);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ident_, implements_, line_num, col_num, offset);
    }

    public <T> T match(Function<ClassDec, T> classDec,
                       Function<InterDec, T> interDec) {
        return classDec.apply(this);
    }

}
