package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class FieldDeclaration implements java.io.Serializable {

    public abstract <T> T match(Function<Dvar, T> dVar,
                                Function<Dmth, T> dMth);

}
