package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class MethodBody implements java.io.Serializable {
    public abstract <T> T match(Function<EmptyMBody, T> emptyMBody,
                                Function<MBody, T> mBody);

}
