package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class Mod extends MulOp {
    public int line_num, col_num, offset;

    public Mod() {
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof Mod) {
            return true;
        }
        return false;
    }

    public int hashCode() {
        return 37;
    }

    public <T> T match(Function<Times, T> times,
                       Function<Div, T> div,
                       Function<Mod, T> mod) {
        return mod.apply(this);
    }


}
