package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public class ObjMethAcc extends ObjAcc {
    public final String ident_;
    public final ListExpr listexpr_;
    public int line_num, col_num, offset;

    public ObjMethAcc(String p1, ListExpr p2) {
        ident_ = p1;
        listexpr_ = p2;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (o instanceof src.Absyn.ObjMethAcc) {
            src.Absyn.ObjMethAcc x = (src.Absyn.ObjMethAcc) o;
            return this.ident_.equals(x.ident_) && this.listexpr_.equals(x.listexpr_);
        }
        return false;
    }

    public int hashCode() {
        return 37 * (this.ident_.hashCode()) + this.listexpr_.hashCode();
    }

    public <T> T match(Function<ObjFieldAcc, T> objFieldAcc,
                       Function<ObjMethAcc, T> objMethAcc) {
        return objMethAcc.apply(this);
    }
}
