package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class Program implements java.io.Serializable {

    public abstract <T> T match(Function<ProgramTD, T> td);

}
