package src.Absyn; // Java Package generated by the BNF Converter.

import java.util.function.Function;

public abstract class TypeName implements java.io.Serializable {

    public abstract <T> T match(Function<BuiltIn, T> builtIn,
                                Function<ClassName, T> className);

}
